package org.gz.risk.auditing.entity;

import java.util.Date;

/**
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table app_user_history
 *
 * @mbg.generated do_not_delete_during_merge
 */
public class UserHistoryEntity {
    /**
     * Database Column Remarks:
     * 用户历史记录id
     * <p>
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column app_user_history.history_id
     *
     * @mbg.generated
     */
    private Long historyId;

    /**
     * Database Column Remarks:
     * 用户编号
     * <p>
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column app_user_history.user_id
     *
     * @mbg.generated
     */
    private Long userId;

    /**
     * Database Column Remarks:
     * 手机号码
     * <p>
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column app_user_history.phone_num
     *
     * @mbg.generated
     */
    private String phoneNum;

    /**
     * Database Column Remarks:
     * 密码
     * <p>
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column app_user_history.password
     *
     * @mbg.generated
     */
    private String password;

    /**
     * Database Column Remarks:
     * 头像
     * <p>
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column app_user_history.avatar
     *
     * @mbg.generated
     */
    private String avatar;

    /**
     * Database Column Remarks:
     * 姓名
     * <p>
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column app_user_history.real_name
     *
     * @mbg.generated
     */
    private String realName;

    /**
     * Database Column Remarks:
     * 身份证号码
     * <p>
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column app_user_history.id_num
     *
     * @mbg.generated
     */
    private String idNum;

    /**
     * Database Column Remarks:
     * 借记卡号码
     * <p>
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column app_user_history.debit_card
     *
     * @mbg.generated
     */
    private String debitCard;

    /**
     * Database Column Remarks:
     * 预留手机号码
     * <p>
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column app_user_history.reserved_phone_num
     *
     * @mbg.generated
     */
    private String reservedPhoneNum;

    /**
     * Database Column Remarks:
     * 学历
     * <p>
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column app_user_history.education
     *
     * @mbg.generated
     */
    private Integer education;

    /**
     * Database Column Remarks:
     * 婚姻状况
     * <p>
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column app_user_history.marital_status
     *
     * @mbg.generated
     */
    private Integer maritalStatus;

    /**
     * Database Column Remarks:
     * 发卡银行
     * <p>
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column app_user_history.card_issuing_bank
     *
     * @mbg.generated
     */
    private String cardIssuingBank;

    /**
     * Database Column Remarks:
     * 公司名称
     * <p>
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column app_user_history.company_name
     *
     * @mbg.generated
     */
    private String companyName;

    /**
     * Database Column Remarks:
     * 公司电话
     * <p>
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column app_user_history.company_cell_num
     *
     * @mbg.generated
     */
    private String companyCellNum;

    /**
     * Database Column Remarks:
     * 公司地址
     * <p>
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column app_user_history.company_address
     *
     * @mbg.generated
     */
    private String companyAddress;

    /**
     * Database Column Remarks:
     * 公司详细地址
     * <p>
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column app_user_history.company_detailed_address
     *
     * @mbg.generated
     */
    private String companyDetailedAddress;

    /**
     * Database Column Remarks:
     * 入职时间
     * <p>
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column app_user_history.entry_time
     *
     * @mbg.generated
     */
    private Date entryTime;

    /**
     * Database Column Remarks:
     * 每月收入
     * <p>
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column app_user_history.income
     *
     * @mbg.generated
     */
    private Integer income;

    /**
     * Database Column Remarks:
     * 紧急联系人
     * <p>
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column app_user_history.emergency_contact
     *
     * @mbg.generated
     */
    private String emergencyContact;

    /**
     * Database Column Remarks:
     * 紧急联系人电话
     * <p>
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column app_user_history.emergency_contact_phone
     *
     * @mbg.generated
     */
    private String emergencyContactPhone;

    /**
     * Database Column Remarks:
     * 手持身份证照片
     * <p>
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column app_user_history.idcard_image1
     *
     * @mbg.generated
     */
    private String idcardImage1;

    /**
     * Database Column Remarks:
     * 身份证正面照片
     * <p>
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column app_user_history.idcard_image2
     *
     * @mbg.generated
     */
    private String idcardImage2;

    /**
     * Database Column Remarks:
     * 身份证反面照片
     * <p>
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column app_user_history.idcard_image3
     *
     * @mbg.generated
     */
    private String idcardImage3;

    /**
     * Database Column Remarks:
     * 户籍城市
     * <p>
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column app_user_history.native_city
     *
     * @mbg.generated
     */
    private String nativeCity;

    /**
     * Database Column Remarks:
     * 户籍地址
     * <p>
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column app_user_history.native_place
     *
     * @mbg.generated
     */
    private String nativePlace;

    /**
     * Database Column Remarks:
     * 子女数目
     * <p>
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column app_user_history.child_total
     *
     * @mbg.generated
     */
    private Integer childTotal;

    /**
     * Database Column Remarks:
     * 现住城市
     * <p>
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column app_user_history.current_city
     *
     * @mbg.generated
     */
    private String currentCity;

    /**
     * Database Column Remarks:
     * 现住地址
     * <p>
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column app_user_history.current_add
     *
     * @mbg.generated
     */
    private String currentAdd;

    /**
     * Database Column Remarks:
     * 单位所属行业(行业类别)
     * <p>
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column app_user_history.industry
     *
     * @mbg.generated
     */
    private String industry;

    /**
     * Database Column Remarks:
     * 单位性质
     * <p>
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column app_user_history.company_type
     *
     * @mbg.generated
     */
    private String companyType;

    /**
     * Database Column Remarks:
     * 职务
     * <p>
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column app_user_history.occupation
     *
     * @mbg.generated
     */
    private String occupation;

    /**
     * Database Column Remarks:
     * 职业
     * <p>
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column app_user_history.position
     *
     * @mbg.generated
     */
    private String position;

    /**
     * Database Column Remarks:
     * 部门
     * <p>
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column app_user_history.department
     *
     * @mbg.generated
     */
    private String department;

    /**
     * Database Column Remarks:
     * 毕业年份
     * <p>
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column app_user_history.graduate_year
     *
     * @mbg.generated
     */
    private Date graduateYear;

    /**
     * Database Column Remarks:
     * 家庭收入
     * <p>
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column app_user_history.familymonth_income
     *
     * @mbg.generated
     */
    private Integer familymonthIncome;

    /**
     * Database Column Remarks:
     * 配偶名称
     * <p>
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column app_user_history.spouse_name
     *
     * @mbg.generated
     */
    private String spouseName;

    /**
     * Database Column Remarks:
     * 配偶电话
     * <p>
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column app_user_history.spouse_tel
     *
     * @mbg.generated
     */
    private String spouseTel;

    /**
     * Database Column Remarks:
     * 亲属姓名
     * <p>
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column app_user_history.kinship_name
     *
     * @mbg.generated
     */
    private String kinshipName;

    /**
     * Database Column Remarks:
     * 亲属电话
     * <p>
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column app_user_history.kinship_tel
     *
     * @mbg.generated
     */
    private String kinshipTel;

    /**
     * Database Column Remarks:
     * 贷款次数
     * <p>
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column app_user_history.loan_times
     *
     * @mbg.generated
     */
    private Integer loanTimes;

    /**
     * Database Column Remarks:
     * 学信网密码
     * <p>
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column app_user_history.xuexin_password
     *
     * @mbg.generated
     */
    private String xuexinPassword;

    /**
     * Database Column Remarks:
     * 上次贷款时间
     * <p>
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column app_user_history.lastloan_date
     *
     * @mbg.generated
     */
    private Date lastloanDate;

    /**
     * Database Column Remarks:
     * 百融生成的唯一标识
     * <p>
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column app_user_history.af_swift_number
     *
     * @mbg.generated
     */
    private String afSwiftNumber;

    /**
     * Database Column Remarks:
     * 信息录入时间
     * <p>
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column app_user_history.input_date
     *
     * @mbg.generated
     */
    private Date inputDate;

    /**
     * Database Column Remarks:
     * qq号
     * <p>
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column app_user_history.qq_num
     *
     * @mbg.generated
     */
    private String qqNum;

    private String companyAreaCode;

    public String getCompanyAreaCode() {
        return companyAreaCode;
    }

    public void setCompanyAreaCode(String companyAreaCode) {
        this.companyAreaCode = companyAreaCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column app_user_history.history_id
     *
     * @return the value of app_user_history.history_id
     * @mbg.generated
     */
    public Long getHistoryId() {
        return historyId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column app_user_history.history_id
     *
     * @param historyId the value for app_user_history.history_id
     * @mbg.generated
     */
    public void setHistoryId(Long historyId) {
        this.historyId = historyId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column app_user_history.user_id
     *
     * @return the value of app_user_history.user_id
     * @mbg.generated
     */
    public Long getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column app_user_history.user_id
     *
     * @param userId the value for app_user_history.user_id
     * @mbg.generated
     */
    public void setUserId(Long userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column app_user_history.phone_num
     *
     * @return the value of app_user_history.phone_num
     * @mbg.generated
     */
    public String getPhoneNum() {
        return phoneNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column app_user_history.phone_num
     *
     * @param phoneNum the value for app_user_history.phone_num
     * @mbg.generated
     */
    public void setPhoneNum(String phoneNum) {
        this.phoneNum = phoneNum == null ? null : phoneNum.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column app_user_history.password
     *
     * @return the value of app_user_history.password
     * @mbg.generated
     */
    public String getPassword() {
        return password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column app_user_history.password
     *
     * @param password the value for app_user_history.password
     * @mbg.generated
     */
    public void setPassword(String password) {
        this.password = password == null ? null : password.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column app_user_history.avatar
     *
     * @return the value of app_user_history.avatar
     * @mbg.generated
     */
    public String getAvatar() {
        return avatar;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column app_user_history.avatar
     *
     * @param avatar the value for app_user_history.avatar
     * @mbg.generated
     */
    public void setAvatar(String avatar) {
        this.avatar = avatar == null ? null : avatar.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column app_user_history.real_name
     *
     * @return the value of app_user_history.real_name
     * @mbg.generated
     */
    public String getRealName() {
        return realName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column app_user_history.real_name
     *
     * @param realName the value for app_user_history.real_name
     * @mbg.generated
     */
    public void setRealName(String realName) {
        this.realName = realName == null ? null : realName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column app_user_history.id_num
     *
     * @return the value of app_user_history.id_num
     * @mbg.generated
     */
    public String getIdNum() {
        return idNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column app_user_history.id_num
     *
     * @param idNum the value for app_user_history.id_num
     * @mbg.generated
     */
    public void setIdNum(String idNum) {
        this.idNum = idNum == null ? null : idNum.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column app_user_history.debit_card
     *
     * @return the value of app_user_history.debit_card
     * @mbg.generated
     */
    public String getDebitCard() {
        return debitCard;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column app_user_history.debit_card
     *
     * @param debitCard the value for app_user_history.debit_card
     * @mbg.generated
     */
    public void setDebitCard(String debitCard) {
        this.debitCard = debitCard == null ? null : debitCard.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column app_user_history.reserved_phone_num
     *
     * @return the value of app_user_history.reserved_phone_num
     * @mbg.generated
     */
    public String getReservedPhoneNum() {
        return reservedPhoneNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column app_user_history.reserved_phone_num
     *
     * @param reservedPhoneNum the value for app_user_history.reserved_phone_num
     * @mbg.generated
     */
    public void setReservedPhoneNum(String reservedPhoneNum) {
        this.reservedPhoneNum = reservedPhoneNum == null ? null : reservedPhoneNum.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column app_user_history.education
     *
     * @return the value of app_user_history.education
     * @mbg.generated
     */
    public Integer getEducation() {
        return education;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column app_user_history.education
     *
     * @param education the value for app_user_history.education
     * @mbg.generated
     */
    public void setEducation(Integer education) {
        this.education = education;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column app_user_history.marital_status
     *
     * @return the value of app_user_history.marital_status
     * @mbg.generated
     */
    public Integer getMaritalStatus() {
        return maritalStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column app_user_history.marital_status
     *
     * @param maritalStatus the value for app_user_history.marital_status
     * @mbg.generated
     */
    public void setMaritalStatus(Integer maritalStatus) {
        this.maritalStatus = maritalStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column app_user_history.card_issuing_bank
     *
     * @return the value of app_user_history.card_issuing_bank
     * @mbg.generated
     */
    public String getCardIssuingBank() {
        return cardIssuingBank;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column app_user_history.card_issuing_bank
     *
     * @param cardIssuingBank the value for app_user_history.card_issuing_bank
     * @mbg.generated
     */
    public void setCardIssuingBank(String cardIssuingBank) {
        this.cardIssuingBank = cardIssuingBank == null ? null : cardIssuingBank.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column app_user_history.company_name
     *
     * @return the value of app_user_history.company_name
     * @mbg.generated
     */
    public String getCompanyName() {
        return companyName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column app_user_history.company_name
     *
     * @param companyName the value for app_user_history.company_name
     * @mbg.generated
     */
    public void setCompanyName(String companyName) {
        this.companyName = companyName == null ? null : companyName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column app_user_history.company_cell_num
     *
     * @return the value of app_user_history.company_cell_num
     * @mbg.generated
     */
    public String getCompanyCellNum() {
        return companyCellNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column app_user_history.company_cell_num
     *
     * @param companyCellNum the value for app_user_history.company_cell_num
     * @mbg.generated
     */
    public void setCompanyCellNum(String companyCellNum) {
        this.companyCellNum = companyCellNum == null ? null : companyCellNum.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column app_user_history.company_address
     *
     * @return the value of app_user_history.company_address
     * @mbg.generated
     */
    public String getCompanyAddress() {
        return companyAddress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column app_user_history.company_address
     *
     * @param companyAddress the value for app_user_history.company_address
     * @mbg.generated
     */
    public void setCompanyAddress(String companyAddress) {
        this.companyAddress = companyAddress == null ? null : companyAddress.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column app_user_history.company_detailed_address
     *
     * @return the value of app_user_history.company_detailed_address
     * @mbg.generated
     */
    public String getCompanyDetailedAddress() {
        return companyDetailedAddress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column app_user_history.company_detailed_address
     *
     * @param companyDetailedAddress the value for app_user_history.company_detailed_address
     * @mbg.generated
     */
    public void setCompanyDetailedAddress(String companyDetailedAddress) {
        this.companyDetailedAddress = companyDetailedAddress == null ? null : companyDetailedAddress.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column app_user_history.entry_time
     *
     * @return the value of app_user_history.entry_time
     * @mbg.generated
     */
    public Date getEntryTime() {
        return entryTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column app_user_history.entry_time
     *
     * @param entryTime the value for app_user_history.entry_time
     * @mbg.generated
     */
    public void setEntryTime(Date entryTime) {
        this.entryTime = entryTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column app_user_history.income
     *
     * @return the value of app_user_history.income
     * @mbg.generated
     */
    public Integer getIncome() {
        return income;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column app_user_history.income
     *
     * @param income the value for app_user_history.income
     * @mbg.generated
     */
    public void setIncome(Integer income) {
        this.income = income;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column app_user_history.emergency_contact
     *
     * @return the value of app_user_history.emergency_contact
     * @mbg.generated
     */
    public String getEmergencyContact() {
        return emergencyContact;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column app_user_history.emergency_contact
     *
     * @param emergencyContact the value for app_user_history.emergency_contact
     * @mbg.generated
     */
    public void setEmergencyContact(String emergencyContact) {
        this.emergencyContact = emergencyContact == null ? null : emergencyContact.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column app_user_history.emergency_contact_phone
     *
     * @return the value of app_user_history.emergency_contact_phone
     * @mbg.generated
     */
    public String getEmergencyContactPhone() {
        return emergencyContactPhone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column app_user_history.emergency_contact_phone
     *
     * @param emergencyContactPhone the value for app_user_history.emergency_contact_phone
     * @mbg.generated
     */
    public void setEmergencyContactPhone(String emergencyContactPhone) {
        this.emergencyContactPhone = emergencyContactPhone == null ? null : emergencyContactPhone.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column app_user_history.idcard_image1
     *
     * @return the value of app_user_history.idcard_image1
     * @mbg.generated
     */
    public String getIdcardImage1() {
        return idcardImage1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column app_user_history.idcard_image1
     *
     * @param idcardImage1 the value for app_user_history.idcard_image1
     * @mbg.generated
     */
    public void setIdcardImage1(String idcardImage1) {
        this.idcardImage1 = idcardImage1 == null ? null : idcardImage1.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column app_user_history.idcard_image2
     *
     * @return the value of app_user_history.idcard_image2
     * @mbg.generated
     */
    public String getIdcardImage2() {
        return idcardImage2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column app_user_history.idcard_image2
     *
     * @param idcardImage2 the value for app_user_history.idcard_image2
     * @mbg.generated
     */
    public void setIdcardImage2(String idcardImage2) {
        this.idcardImage2 = idcardImage2 == null ? null : idcardImage2.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column app_user_history.idcard_image3
     *
     * @return the value of app_user_history.idcard_image3
     * @mbg.generated
     */
    public String getIdcardImage3() {
        return idcardImage3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column app_user_history.idcard_image3
     *
     * @param idcardImage3 the value for app_user_history.idcard_image3
     * @mbg.generated
     */
    public void setIdcardImage3(String idcardImage3) {
        this.idcardImage3 = idcardImage3 == null ? null : idcardImage3.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column app_user_history.native_city
     *
     * @return the value of app_user_history.native_city
     * @mbg.generated
     */
    public String getNativeCity() {
        return nativeCity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column app_user_history.native_city
     *
     * @param nativeCity the value for app_user_history.native_city
     * @mbg.generated
     */
    public void setNativeCity(String nativeCity) {
        this.nativeCity = nativeCity == null ? null : nativeCity.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column app_user_history.native_place
     *
     * @return the value of app_user_history.native_place
     * @mbg.generated
     */
    public String getNativePlace() {
        return nativePlace;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column app_user_history.native_place
     *
     * @param nativePlace the value for app_user_history.native_place
     * @mbg.generated
     */
    public void setNativePlace(String nativePlace) {
        this.nativePlace = nativePlace == null ? null : nativePlace.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column app_user_history.child_total
     *
     * @return the value of app_user_history.child_total
     * @mbg.generated
     */
    public Integer getChildTotal() {
        return childTotal;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column app_user_history.child_total
     *
     * @param childTotal the value for app_user_history.child_total
     * @mbg.generated
     */
    public void setChildTotal(Integer childTotal) {
        this.childTotal = childTotal;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column app_user_history.current_city
     *
     * @return the value of app_user_history.current_city
     * @mbg.generated
     */
    public String getCurrentCity() {
        return currentCity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column app_user_history.current_city
     *
     * @param currentCity the value for app_user_history.current_city
     * @mbg.generated
     */
    public void setCurrentCity(String currentCity) {
        this.currentCity = currentCity == null ? null : currentCity.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column app_user_history.current_add
     *
     * @return the value of app_user_history.current_add
     * @mbg.generated
     */
    public String getCurrentAdd() {
        return currentAdd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column app_user_history.current_add
     *
     * @param currentAdd the value for app_user_history.current_add
     * @mbg.generated
     */
    public void setCurrentAdd(String currentAdd) {
        this.currentAdd = currentAdd == null ? null : currentAdd.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column app_user_history.industry
     *
     * @return the value of app_user_history.industry
     * @mbg.generated
     */
    public String getIndustry() {
        return industry;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column app_user_history.industry
     *
     * @param industry the value for app_user_history.industry
     * @mbg.generated
     */
    public void setIndustry(String industry) {
        this.industry = industry == null ? null : industry.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column app_user_history.company_type
     *
     * @return the value of app_user_history.company_type
     * @mbg.generated
     */
    public String getCompanyType() {
        return companyType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column app_user_history.company_type
     *
     * @param companyType the value for app_user_history.company_type
     * @mbg.generated
     */
    public void setCompanyType(String companyType) {
        this.companyType = companyType == null ? null : companyType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column app_user_history.occupation
     *
     * @return the value of app_user_history.occupation
     * @mbg.generated
     */
    public String getOccupation() {
        return occupation;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column app_user_history.occupation
     *
     * @param occupation the value for app_user_history.occupation
     * @mbg.generated
     */
    public void setOccupation(String occupation) {
        this.occupation = occupation == null ? null : occupation.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column app_user_history.position
     *
     * @return the value of app_user_history.position
     * @mbg.generated
     */
    public String getPosition() {
        return position;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column app_user_history.position
     *
     * @param position the value for app_user_history.position
     * @mbg.generated
     */
    public void setPosition(String position) {
        this.position = position == null ? null : position.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column app_user_history.department
     *
     * @return the value of app_user_history.department
     * @mbg.generated
     */
    public String getDepartment() {
        return department;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column app_user_history.department
     *
     * @param department the value for app_user_history.department
     * @mbg.generated
     */
    public void setDepartment(String department) {
        this.department = department == null ? null : department.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column app_user_history.graduate_year
     *
     * @return the value of app_user_history.graduate_year
     * @mbg.generated
     */
    public Date getGraduateYear() {
        return graduateYear;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column app_user_history.graduate_year
     *
     * @param graduateYear the value for app_user_history.graduate_year
     * @mbg.generated
     */
    public void setGraduateYear(Date graduateYear) {
        this.graduateYear = graduateYear;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column app_user_history.familymonth_income
     *
     * @return the value of app_user_history.familymonth_income
     * @mbg.generated
     */
    public Integer getFamilymonthIncome() {
        return familymonthIncome;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column app_user_history.familymonth_income
     *
     * @param familymonthIncome the value for app_user_history.familymonth_income
     * @mbg.generated
     */
    public void setFamilymonthIncome(Integer familymonthIncome) {
        this.familymonthIncome = familymonthIncome;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column app_user_history.spouse_name
     *
     * @return the value of app_user_history.spouse_name
     * @mbg.generated
     */
    public String getSpouseName() {
        return spouseName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column app_user_history.spouse_name
     *
     * @param spouseName the value for app_user_history.spouse_name
     * @mbg.generated
     */
    public void setSpouseName(String spouseName) {
        this.spouseName = spouseName == null ? null : spouseName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column app_user_history.spouse_tel
     *
     * @return the value of app_user_history.spouse_tel
     * @mbg.generated
     */
    public String getSpouseTel() {
        return spouseTel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column app_user_history.spouse_tel
     *
     * @param spouseTel the value for app_user_history.spouse_tel
     * @mbg.generated
     */
    public void setSpouseTel(String spouseTel) {
        this.spouseTel = spouseTel == null ? null : spouseTel.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column app_user_history.kinship_name
     *
     * @return the value of app_user_history.kinship_name
     * @mbg.generated
     */
    public String getKinshipName() {
        return kinshipName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column app_user_history.kinship_name
     *
     * @param kinshipName the value for app_user_history.kinship_name
     * @mbg.generated
     */
    public void setKinshipName(String kinshipName) {
        this.kinshipName = kinshipName == null ? null : kinshipName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column app_user_history.kinship_tel
     *
     * @return the value of app_user_history.kinship_tel
     * @mbg.generated
     */
    public String getKinshipTel() {
        return kinshipTel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column app_user_history.kinship_tel
     *
     * @param kinshipTel the value for app_user_history.kinship_tel
     * @mbg.generated
     */
    public void setKinshipTel(String kinshipTel) {
        this.kinshipTel = kinshipTel == null ? null : kinshipTel.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column app_user_history.loan_times
     *
     * @return the value of app_user_history.loan_times
     * @mbg.generated
     */
    public Integer getLoanTimes() {
        return loanTimes;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column app_user_history.loan_times
     *
     * @param loanTimes the value for app_user_history.loan_times
     * @mbg.generated
     */
    public void setLoanTimes(Integer loanTimes) {
        this.loanTimes = loanTimes;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column app_user_history.xuexin_password
     *
     * @return the value of app_user_history.xuexin_password
     * @mbg.generated
     */
    public String getXuexinPassword() {
        return xuexinPassword;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column app_user_history.xuexin_password
     *
     * @param xuexinPassword the value for app_user_history.xuexin_password
     * @mbg.generated
     */
    public void setXuexinPassword(String xuexinPassword) {
        this.xuexinPassword = xuexinPassword == null ? null : xuexinPassword.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column app_user_history.lastloan_date
     *
     * @return the value of app_user_history.lastloan_date
     * @mbg.generated
     */
    public Date getLastloanDate() {
        return lastloanDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column app_user_history.lastloan_date
     *
     * @param lastloanDate the value for app_user_history.lastloan_date
     * @mbg.generated
     */
    public void setLastloanDate(Date lastloanDate) {
        this.lastloanDate = lastloanDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column app_user_history.af_swift_number
     *
     * @return the value of app_user_history.af_swift_number
     * @mbg.generated
     */
    public String getAfSwiftNumber() {
        return afSwiftNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column app_user_history.af_swift_number
     *
     * @param afSwiftNumber the value for app_user_history.af_swift_number
     * @mbg.generated
     */
    public void setAfSwiftNumber(String afSwiftNumber) {
        this.afSwiftNumber = afSwiftNumber == null ? null : afSwiftNumber.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column app_user_history.input_date
     *
     * @return the value of app_user_history.input_date
     * @mbg.generated
     */
    public Date getInputDate() {
        return inputDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column app_user_history.input_date
     *
     * @param inputDate the value for app_user_history.input_date
     * @mbg.generated
     */
    public void setInputDate(Date inputDate) {
        this.inputDate = inputDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column app_user_history.qq_num
     *
     * @return the value of app_user_history.qq_num
     * @mbg.generated
     */
    public String getQqNum() {
        return qqNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column app_user_history.qq_num
     *
     * @param qqNum the value for app_user_history.qq_num
     * @mbg.generated
     */
    public void setQqNum(String qqNum) {
        this.qqNum = qqNum == null ? null : qqNum.trim();
    }
}