package org.gz.risk.auditing.entity;

import java.io.Serializable;
import java.util.Date;

/**
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table admin_violation
 *
 * @mbg.generated do_not_delete_during_merge
 */
public class ViolationEntity implements Serializable{
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column admin_violation.violation_id
     *
     * @mbg.generated
     */
    private Long violationId;

    /**
     * Database Column Remarks:
     *   Υ���
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column admin_violation.violation_key
     *
     * @mbg.generated
     */
    private String violationKey;

    /**
     * Database Column Remarks:
     *   Υ��ֵ
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column admin_violation.violation_value
     *
     * @mbg.generated
     */
    private String violationValue;

    /**
     * Database Column Remarks:
     *   Υ������
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column admin_violation.meal
     *
     * @mbg.generated
     */
    private String meal;

    /**
     * Database Column Remarks:
     *   �����ĸ��û�
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column admin_violation.user_id
     *
     * @mbg.generated
     */
    private Long userId;

    /**
     * Database Column Remarks:
     *   �����ĸ�ƽ̨
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column admin_violation.belong
     *
     * @mbg.generated
     */
    private Integer belong;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column admin_violation.loan_record
     *
     * @mbg.generated
     */
    private String loanRecord;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column admin_violation.input_time
     *
     * @mbg.generated
     */
    private Date inputTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column admin_violation.violation_id
     *
     * @return the value of admin_violation.violation_id
     *
     * @mbg.generated
     */
    public Long getViolationId() {
        return violationId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column admin_violation.violation_id
     *
     * @param violationId the value for admin_violation.violation_id
     *
     * @mbg.generated
     */
    public void setViolationId(Long violationId) {
        this.violationId = violationId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column admin_violation.violation_key
     *
     * @return the value of admin_violation.violation_key
     *
     * @mbg.generated
     */
    public String getViolationKey() {
        return violationKey;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column admin_violation.violation_key
     *
     * @param violationKey the value for admin_violation.violation_key
     *
     * @mbg.generated
     */
    public void setViolationKey(String violationKey) {
        this.violationKey = violationKey == null ? null : violationKey.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column admin_violation.violation_value
     *
     * @return the value of admin_violation.violation_value
     *
     * @mbg.generated
     */
    public String getViolationValue() {
        return violationValue;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column admin_violation.violation_value
     *
     * @param violationValue the value for admin_violation.violation_value
     *
     * @mbg.generated
     */
    public void setViolationValue(String violationValue) {
        this.violationValue = violationValue == null ? null : violationValue.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column admin_violation.meal
     *
     * @return the value of admin_violation.meal
     *
     * @mbg.generated
     */
    public String getMeal() {
        return meal;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column admin_violation.meal
     *
     * @param meal the value for admin_violation.meal
     *
     * @mbg.generated
     */
    public void setMeal(String meal) {
        this.meal = meal == null ? null : meal.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column admin_violation.user_id
     *
     * @return the value of admin_violation.user_id
     *
     * @mbg.generated
     */
    public Long getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column admin_violation.user_id
     *
     * @param userId the value for admin_violation.user_id
     *
     * @mbg.generated
     */
    public void setUserId(Long userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column admin_violation.belong
     *
     * @return the value of admin_violation.belong
     *
     * @mbg.generated
     */
    public Integer getBelong() {
        return belong;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column admin_violation.belong
     *
     * @param belong the value for admin_violation.belong
     *
     * @mbg.generated
     */
    public void setBelong(Integer belong) {
        this.belong = belong;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column admin_violation.loan_record
     *
     * @return the value of admin_violation.loan_record
     *
     * @mbg.generated
     */
    public String getLoanRecord() {
        return loanRecord;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column admin_violation.loan_record
     *
     * @param loanRecord the value for admin_violation.loan_record
     *
     * @mbg.generated
     */
    public void setLoanRecord(String loanRecord) {
        this.loanRecord = loanRecord == null ? null : loanRecord.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column admin_violation.input_time
     *
     * @return the value of admin_violation.input_time
     *
     * @mbg.generated
     */
    public Date getInputTime() {
        return inputTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column admin_violation.input_time
     *
     * @param inputTime the value for admin_violation.input_time
     *
     * @mbg.generated
     */
    public void setInputTime(Date inputTime) {
        this.inputTime = inputTime;
    }
}